# Generated by Django 6.0.4 on 2026-04-27 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='attention',
            field=models.FloatField(default=0.0),
        ),
    ]
